// Generated by pnpm contracts:generate from contracts/core-v0.1.mjs.
// JSON Schema performs runtime validation; TypeScript alone does not validate JSON.

export type Id = string;

export type Revision = string;

export type VlanIntent = ({
  "mode": "access";
  "tag": number;
  "trunks": Array<number>;
}) | ({
  "mode": "trunk";
  "tag": null;
  "trunks": Array<number>;
}) | ({
  "mode": "native-tagged";
  "tag": number;
  "trunks": Array<number>;
});

export type NativeVlan = {
  "mode": (string) | (null);
  "tag": (number) | (null);
  "trunks": Array<number>;
};

export type VlanObservation = ({
  "availability": "known";
  "value": VlanIntent;
  "native": NativeVlan;
}) | ({
  "availability": "unsupported";
  "value": null;
  "native": NativeVlan;
  "reason": string;
}) | ({
  "availability": "unknown" | "unavailable";
  "value": null;
  "native": null;
  "reason": string;
});

export type PortResource = {
  "id": Id;
  "nodeId": Id;
  "name": string;
  "bridgeId": Id;
  "interfaces": Array<{
  "id": Id;
  "name": string;
}>;
  "kind": "single" | "bond";
  "scope": "manage" | "basic-manage" | "observe";
  "authority": "ovs" | "external" | "unknown";
  "provider": string;
  "configuration": VlanObservation;
  "linkState": "up" | "down" | "unknown";
  "linkReason": (string) | (null);
  "speedMbps": (number) | (null);
  "observedAt": string;
  "generation": Revision;
  "writableFields": Array<"vlan">;
};

export type PortsPage = {
  "nodeId": Id;
  "generation": Revision;
  "observedAt": string;
  "snapshotId": Id;
  "availability": "complete" | "degraded";
  "items": Array<PortResource>;
  "warnings": Array<string>;
  "nextCursor": (string) | (null);
};

export type VlanChange = {
  "id": Id;
  "portId": Id;
  "base": VlanIntent;
  "mine": VlanIntent;
};

export type VlanConflict = {
  "intentId": Id;
  "portId": Id;
  "field": "vlan";
  "base": VlanIntent;
  "current": VlanIntent;
  "mine": VlanIntent;
};

export type CandidateResource = {
  "id": Id;
  "nodeId": Id;
  "revision": Revision;
  "baseGeneration": Revision;
  "currentGeneration": Revision;
  "freshness": "current" | "stale" | "conflict";
  "intents": Array<VlanChange>;
  "conflicts": Array<VlanConflict>;
  "conflictSnapshotId": (Id) | (null);
  "lockedByTransactionId": (Id) | (null);
  "updatedAt": string;
};

export type CandidateMutation = ({
  "requestId": Id;
  "operation": "set-vlan";
  "portId": Id;
  "mine": VlanIntent;
  "expectedGeneration": Revision;
}) | ({
  "requestId": Id;
  "operation": "discard";
}) | ({
  "requestId": Id;
  "operation": "rebase";
  "currentGeneration": Revision;
  "conflictSnapshotId": (Id) | (null);
  "resolutions": Array<{
  "intentId": Id;
  "choice": "current" | "mine";
}>;
});

export type ValidationRequest = {
  "requestId": Id;
  "candidateId": Id;
  "expectedCandidateRevision": Revision;
  "expectedGeneration": Revision;
};

export type ValidationCheck = {
  "code": string;
  "state": "pass" | "warning" | "block" | "unknown";
  "message": string;
  "portId": (Id) | (null);
};

export type SafetyPlan = {
  "checkpoint": "available" | "unavailable" | "unknown";
  "connectivityProbe": "available" | "unavailable" | "unknown";
  "compareBeforeRollback": "available" | "unavailable" | "unknown";
  "confirmationWindowSeconds": number;
  "reauthenticationRequired": boolean;
};

export type ValidationResource = {
  "id": Id;
  "nodeId": Id;
  "requestId": Id;
  "jobId": Id;
  "candidateId": Id;
  "candidateRevision": Revision;
  "generation": Revision;
  "policyRevision": Revision;
  "status": "pending" | "running" | "passed" | "blocked" | "expired";
  "expiresAt": (string) | (null);
  "checks": Array<ValidationCheck>;
  "diff": Array<VlanChange>;
  "safetyPlan": (SafetyPlan) | (null);
};

export type StartSafeApplyRequest = {
  "requestId": Id;
  "candidateId": Id;
  "expectedCandidateRevision": Revision;
  "expectedGeneration": Revision;
  "validationId": Id;
  "reason": string;
  "reauthenticationProof"?: string;
};

export type TransactionEvidence = {
  "databaseCommit": "pending" | "committed" | "not-committed" | "unknown";
  "daemonApply": "pending" | "applied" | "failed" | "unknown";
  "health": "pending" | "passed" | "failed" | "unknown";
  "checkpoint": "pending" | "ready" | "unavailable" | "unknown";
  "desiredGeneration": (Revision) | (null);
  "observedGeneration": (Revision) | (null);
  "nextCfg": (string) | (null);
  "curCfg": (string) | (null);
};

export type TransactionResource = {
  "id": Id;
  "nodeId": Id;
  "requestId": Id;
  "candidateId": Id;
  "candidateRevision": Revision;
  "jobId": Id;
  "correlationId": Id;
  "sequence": number;
  "serverTime": string;
  "knowledge": "current" | "outcome-unknown";
  "phase": "queued" | "preflight" | "committing" | "applying" | "awaiting-confirmation" | "rolling-back" | "settled";
  "outcome": "unknown" | "applied" | "not-applied" | "degraded" | "needs-attention";
  "safeApply": "not-started" | "armed" | "awaiting-confirmation" | "confirming" | "confirmed" | "rollback-requested" | "rolled-back" | "rollback-conflict";
  "confirmationDeadline": (string) | (null);
  "locksCandidate": boolean;
  "allowedActions": Array<"read" | "reconcile" | "confirm" | "rollback">;
  "evidence": TransactionEvidence;
};

export type DecisionRequest = {
  "requestId": Id;
  "expectedTransactionSequence": number;
  "decision": "confirm" | "rollback";
  "reason": string;
  "reauthenticationProof"?: string;
};

export type ReconciliationRequest = {
  "requestId": Id;
};

export type JobResource = {
  "id": Id;
  "nodeId": Id;
  "kind": "validation" | "safe-apply" | "reconciliation" | "drift-read";
  "state": "queued" | "running" | "succeeded" | "failed" | "cancelled" | "unknown";
  "transactionId": (Id) | (null);
  "correlationId": Id;
  "updatedAt": string;
  "message": string;
};

export type Problem = {
  "type": string;
  "title": string;
  "status": number;
  "detail": string;
  "instance": string;
  "code": "UNAUTHENTICATED" | "FORBIDDEN" | "REAUTH_REQUIRED" | "ETAG_MISMATCH" | "PRECONDITION_REQUIRED" | "CANDIDATE_STALE" | "FIELD_CONFLICT" | "VALIDATION_EXPIRED" | "VALIDATION_BLOCKED" | "TRANSACTION_ACTIVE" | "DECISION_EXPIRED" | "TRANSACTION_VERSION_CHANGED" | "IDEMPOTENCY_MISMATCH" | "UNSUPPORTED_CONFIGURATION" | "INVALID_INTENT" | "PROVIDER_UNAVAILABLE" | "OUTCOME_UNKNOWN" | "NOT_FOUND" | "INTERNAL_ERROR";
  "requestId": Id;
  "correlationId": Id;
  "commandEffect": "not-started" | "unknown";
  "transactionId": (Id) | (null);
  "candidateRevision": (Revision) | (null);
};

export type RequestRecord = {
  "requestId": Id;
  "nodeId": Id;
  "operation": "candidate" | "validation" | "safe-apply" | "decision" | "reconciliation" | "drift-read";
  "state": "recorded" | "accepted" | "rejected";
  "recordedAt": string;
  "transactionId": (Id) | (null);
  "jobId": (Id) | (null);
  "validationId": (Id) | (null);
  "candidateRevision": (Revision) | (null);
  "problem": (Problem) | (null);
};

export type WorkspaceSnapshot = {
  "nodeId": Id;
  "serverTime": string;
  "candidate": CandidateResource;
  "latestValidation": (ValidationResource) | (null);
  "activeTransactions": Array<TransactionResource>;
  "pendingRequests": Array<RequestRecord>;
  "nodeWriteBlocked": boolean;
  "permissions": {
  "editCandidate": boolean;
  "validate": boolean;
  "startSafeApply": boolean;
};
};

export type DriftReport = {
  "id": Id;
  "nodeId": Id;
  "observedAt": string;
  "desiredGeneration": Revision;
  "observedGeneration": (Revision) | (null);
  "status": "in-sync" | "drift" | "unknown";
  "items": Array<{
  "portId": Id;
  "desired": VlanIntent;
  "observed": VlanObservation;
}>;
};

export type EvidenceEntry = {
  "id": Id;
  "kind": "audit" | "event" | "job" | "health";
  "occurredAt": string;
  "nodeId": Id;
  "transactionId": Id;
  "requestId": Id;
  "correlationId": Id;
  "objectId": Id;
  "code": string;
  "summary": string;
};

export type EvidencePage = {
  "items": Array<EvidenceEntry>;
  "nextCursor": (string) | (null);
};
