// Generated by pnpm contracts:generate.
import type { HttpSchemas } from './http-client';
export function validateContract(name: keyof HttpSchemas, value: unknown): boolean;
export const validators: Record<keyof HttpSchemas, (value: unknown) => boolean>;
