// Code generated by scripts/generate-public-contract.mjs; DO NOT EDIT.
package apidto

import "encoding/json"

type Id string
type RequestId string
type Revision string
type Sequence string
type DateTime string
type RequestDomain string
type ObservedRequestDomain string
type ResourceRef struct {
	Kind        string                     `json:"kind"`
	Id          Id                         `json:"id"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *ResourceRef) UnmarshalJSON(data []byte) error {
	type plain ResourceRef
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ResourceRef) MarshalJSON() ([]byte, error) {
	type plain ResourceRef
	return encodeOpen(plain(v), v.ExtraFields)
}

type ObjectBinding struct {
	ManagementId       Id     `json:"management_id"`
	OvsUuid            string `json:"ovs_uuid"`
	Table              string `json:"table"`
	InstanceGeneration Id     `json:"instance_generation"`
}
type ObservedBinding struct {
	ManagementId       Id                         `json:"management_id"`
	OvsUuid            string                     `json:"ovs_uuid"`
	Table              string                     `json:"table"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *ObservedBinding) UnmarshalJSON(data []byte) error {
	type plain ObservedBinding
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ObservedBinding) MarshalJSON() ([]byte, error) {
	type plain ObservedBinding
	return encodeOpen(plain(v), v.ExtraFields)
}

type Source struct {
	ProviderId  string                     `json:"provider_id"`
	Authority   string                     `json:"authority"`
	ObservedAt  json.RawMessage            `json:"observed_at"`
	Freshness   string                     `json:"freshness"`
	Confidence  string                     `json:"confidence"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *Source) UnmarshalJSON(data []byte) error {
	type plain Source
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Source) MarshalJSON() ([]byte, error) {
	type plain Source
	return encodeOpen(plain(v), v.ExtraFields)
}

type NativeVlan struct {
	VlanMode    json.RawMessage            `json:"vlan_mode"`
	Tag         json.RawMessage            `json:"tag"`
	Trunks      []int64                    `json:"trunks"`
	Cvlans      []int64                    `json:"cvlans"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *NativeVlan) UnmarshalJSON(data []byte) error {
	type plain NativeVlan
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v NativeVlan) MarshalJSON() ([]byte, error) {
	type plain NativeVlan
	return encodeOpen(plain(v), v.ExtraFields)
}

type VlanObservation struct {
	Availability string                     `json:"availability"`
	Native       json.RawMessage            `json:"native"`
	Source       Source                     `json:"source"`
	Reason       json.RawMessage            `json:"reason"`
	ExtraFields  map[string]json.RawMessage `json:"-"`
}

func (v *VlanObservation) UnmarshalJSON(data []byte) error {
	type plain VlanObservation
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v VlanObservation) MarshalJSON() ([]byte, error) {
	type plain VlanObservation
	return encodeOpen(plain(v), v.ExtraFields)
}

type VlanInput = json.RawMessage
type VlanIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
	Value     VlanInput     `json:"value"`
}
type ObservedIntent struct {
	IntentId    Id                         `json:"intent_id"`
	Operation   string                     `json:"operation"`
	Object      ObservedBinding            `json:"object"`
	Value       map[string]json.RawMessage `json:"value"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *ObservedIntent) UnmarshalJSON(data []byte) error {
	type plain ObservedIntent
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ObservedIntent) MarshalJSON() ([]byte, error) {
	type plain ObservedIntent
	return encodeOpen(plain(v), v.ExtraFields)
}

type Port struct {
	ManagementId       Id                         `json:"management_id"`
	OvsUuid            string                     `json:"ovs_uuid"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ConfigRevision     Revision                   `json:"config_revision"`
	Name               string                     `json:"name"`
	BridgeRef          ResourceRef                `json:"bridge_ref"`
	InterfaceRefs      []ResourceRef              `json:"interface_refs"`
	Kind               string                     `json:"kind"`
	Vlan               VlanObservation            `json:"vlan"`
	OvsLinkState       map[string]json.RawMessage `json:"ovs_link_state"`
	LinuxCarrier       map[string]json.RawMessage `json:"linux_carrier"`
	AllowedOperations  []string                   `json:"allowed_operations"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Port) UnmarshalJSON(data []byte) error {
	type plain Port
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Port) MarshalJSON() ([]byte, error) {
	type plain Port
	return encodeOpen(plain(v), v.ExtraFields)
}

type PortsPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration Id                         `json:"instance_generation"`
	Source             Source                     `json:"source"`
	Availability       string                     `json:"availability"`
	Items              []Port                     `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *PortsPage) UnmarshalJSON(data []byte) error {
	type plain PortsPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v PortsPage) MarshalJSON() ([]byte, error) {
	type plain PortsPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type Candidate struct {
	Id                 Id                         `json:"id"`
	Revision           Revision                   `json:"revision"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	BaseConfigRevision json.RawMessage            `json:"base_config_revision"`
	State              string                     `json:"state"`
	Intents            []ObservedIntent           `json:"intents"`
	ConsumedBy         json.RawMessage            `json:"consumed_by"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Candidate) UnmarshalJSON(data []byte) error {
	type plain Candidate
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Candidate) MarshalJSON() ([]byte, error) {
	type plain Candidate
	return encodeOpen(plain(v), v.ExtraFields)
}

type Resolution struct {
	IntentId Id     `json:"intent_id"`
	Choice   string `json:"choice"`
}
type CandidateCommand = json.RawMessage
type Gate struct {
	Code        string                     `json:"code"`
	State       string                     `json:"state"`
	Reason      string                     `json:"reason"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *Gate) UnmarshalJSON(data []byte) error {
	type plain Gate
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Gate) MarshalJSON() ([]byte, error) {
	type plain Gate
	return encodeOpen(plain(v), v.ExtraFields)
}

type Session struct {
	PrincipalId           Id                         `json:"principal_id"`
	DisplayName           string                     `json:"display_name"`
	EffectiveCapabilities []string                   `json:"effective_capabilities"`
	ExpiresAt             DateTime                   `json:"expires_at"`
	CsrfToken             string                     `json:"csrf_token"`
	RequestEpochs         map[string]json.RawMessage `json:"request_epochs"`
	ServerTime            DateTime                   `json:"server_time"`
	ExtraFields           map[string]json.RawMessage `json:"-"`
}

func (v *Session) UnmarshalJSON(data []byte) error {
	type plain Session
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Session) MarshalJSON() ([]byte, error) {
	type plain Session
	return encodeOpen(plain(v), v.ExtraFields)
}

type Login struct {
	Provider string `json:"provider"`
	Username string `json:"username"`
	Password string `json:"password"`
}
type Workspace struct {
	ServerTime        DateTime                   `json:"server_time"`
	RequestEpochs     map[string]json.RawMessage `json:"request_epochs"`
	Candidate         json.RawMessage            `json:"candidate"`
	LatestValidation  json.RawMessage            `json:"latest_validation"`
	LatestTransaction json.RawMessage            `json:"latest_transaction"`
	Gates             []Gate                     `json:"gates"`
	ExtraFields       map[string]json.RawMessage `json:"-"`
}

func (v *Workspace) UnmarshalJSON(data []byte) error {
	type plain Workspace
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Workspace) MarshalJSON() ([]byte, error) {
	type plain Workspace
	return encodeOpen(plain(v), v.ExtraFields)
}

type ValidationCommand struct {
	RequestId         RequestId `json:"request_id"`
	CandidateId       Id        `json:"candidate_id"`
	CandidateRevision Revision  `json:"candidate_revision"`
}
type DiffField struct {
	Object      ObservedBinding            `json:"object"`
	Field       string                     `json:"field"`
	Before      json.RawMessage            `json:"before"`
	After       json.RawMessage            `json:"after"`
	Authority   string                     `json:"authority"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *DiffField) UnmarshalJSON(data []byte) error {
	type plain DiffField
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v DiffField) MarshalJSON() ([]byte, error) {
	type plain DiffField
	return encodeOpen(plain(v), v.ExtraFields)
}

type Validation struct {
	Id                 Id                         `json:"id"`
	CandidateId        Id                         `json:"candidate_id"`
	CandidateRevision  Revision                   `json:"candidate_revision"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ConfigRevision     Revision                   `json:"config_revision"`
	PolicyRevision     Revision                   `json:"policy_revision"`
	ExpiresAt          DateTime                   `json:"expires_at"`
	JobRef             ResourceRef                `json:"job_ref"`
	State              string                     `json:"state"`
	Checks             []Gate                     `json:"checks"`
	Diff               []DiffField                `json:"diff"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Validation) UnmarshalJSON(data []byte) error {
	type plain Validation
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Validation) MarshalJSON() ([]byte, error) {
	type plain Validation
	return encodeOpen(plain(v), v.ExtraFields)
}

type TransactionCommand struct {
	RequestId         RequestId `json:"request_id"`
	CandidateId       Id        `json:"candidate_id"`
	CandidateRevision Revision  `json:"candidate_revision"`
	ValidationId      Id        `json:"validation_id"`
	Mode              string    `json:"mode"`
	Reason            string    `json:"reason"`
}
type DecisionCommand struct {
	RequestId        RequestId `json:"request_id"`
	Decision         string    `json:"decision"`
	ExpectedSequence Sequence  `json:"expected_sequence"`
}
type ReconciliationCommand struct {
	RequestId RequestId `json:"request_id"`
}
type AppliedEvidence struct {
	ProviderId         string                     `json:"provider_id"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ObservedAt         json.RawMessage            `json:"observed_at"`
	NextCfgTarget      json.RawMessage            `json:"next_cfg_target"`
	CurCfg             json.RawMessage            `json:"cur_cfg"`
	State              string                     `json:"state"`
	Reason             json.RawMessage            `json:"reason"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *AppliedEvidence) UnmarshalJSON(data []byte) error {
	type plain AppliedEvidence
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v AppliedEvidence) MarshalJSON() ([]byte, error) {
	type plain AppliedEvidence
	return encodeOpen(plain(v), v.ExtraFields)
}

type Transaction struct {
	Id                   Id                         `json:"id"`
	InstanceGeneration   Id                         `json:"instance_generation"`
	Sequence             Sequence                   `json:"sequence"`
	Phase                string                     `json:"phase"`
	Knowledge            string                     `json:"knowledge"`
	CommitOutcome        string                     `json:"commit_outcome"`
	AppliedOutcome       string                     `json:"applied_outcome"`
	SafeApply            string                     `json:"safe_apply"`
	Health               string                     `json:"health"`
	AppliedEvidence      AppliedEvidence            `json:"applied_evidence"`
	ConfirmationDeadline json.RawMessage            `json:"confirmation_deadline"`
	ServerTime           DateTime                   `json:"server_time"`
	AllowedActions       []string                   `json:"allowed_actions"`
	JobRef               ResourceRef                `json:"job_ref"`
	CorrelationId        Id                         `json:"correlation_id"`
	ExtraFields          map[string]json.RawMessage `json:"-"`
}

func (v *Transaction) UnmarshalJSON(data []byte) error {
	type plain Transaction
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Transaction) MarshalJSON() ([]byte, error) {
	type plain Transaction
	return encodeOpen(plain(v), v.ExtraFields)
}

type Accepted struct {
	RequestId     RequestId                  `json:"request_id"`
	RequestDomain ObservedRequestDomain      `json:"request_domain"`
	RequestEpoch  Id                         `json:"request_epoch"`
	JobId         Id                         `json:"job_id"`
	ResourceRef   ResourceRef                `json:"resource_ref"`
	CorrelationId Id                         `json:"correlation_id"`
	ExtraFields   map[string]json.RawMessage `json:"-"`
}

func (v *Accepted) UnmarshalJSON(data []byte) error {
	type plain Accepted
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Accepted) MarshalJSON() ([]byte, error) {
	type plain Accepted
	return encodeOpen(plain(v), v.ExtraFields)
}

type RequestReceipt struct {
	RequestId     RequestId                  `json:"request_id"`
	RequestDomain ObservedRequestDomain      `json:"request_domain"`
	RequestEpoch  Id                         `json:"request_epoch"`
	State         string                     `json:"state"`
	CommandEffect string                     `json:"command_effect"`
	ResourceRef   json.RawMessage            `json:"resource_ref"`
	JobRef        json.RawMessage            `json:"job_ref"`
	CorrelationId Id                         `json:"correlation_id"`
	ExtraFields   map[string]json.RawMessage `json:"-"`
}

func (v *RequestReceipt) UnmarshalJSON(data []byte) error {
	type plain RequestReceipt
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v RequestReceipt) MarshalJSON() ([]byte, error) {
	type plain RequestReceipt
	return encodeOpen(plain(v), v.ExtraFields)
}

type Job struct {
	Id            Id                         `json:"id"`
	Sequence      Sequence                   `json:"sequence"`
	State         string                     `json:"state"`
	Operation     string                     `json:"operation"`
	OwnerId       Id                         `json:"owner_id"`
	ResourceRef   json.RawMessage            `json:"resource_ref"`
	Cancellable   bool                       `json:"cancellable"`
	CorrelationId Id                         `json:"correlation_id"`
	ExtraFields   map[string]json.RawMessage `json:"-"`
}

func (v *Job) UnmarshalJSON(data []byte) error {
	type plain Job
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Job) MarshalJSON() ([]byte, error) {
	type plain Job
	return encodeOpen(plain(v), v.ExtraFields)
}

type EvidenceEntry struct {
	Id            Id                         `json:"id"`
	Kind          string                     `json:"kind"`
	OccurredAt    DateTime                   `json:"occurred_at"`
	Code          string                     `json:"code"`
	ObjectRefs    []ResourceRef              `json:"object_refs"`
	CorrelationId json.RawMessage            `json:"correlation_id"`
	Summary       string                     `json:"summary"`
	ExtraFields   map[string]json.RawMessage `json:"-"`
}

func (v *EvidenceEntry) UnmarshalJSON(data []byte) error {
	type plain EvidenceEntry
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v EvidenceEntry) MarshalJSON() ([]byte, error) {
	type plain EvidenceEntry
	return encodeOpen(plain(v), v.ExtraFields)
}

type EvidencePage struct {
	Items       []EvidenceEntry            `json:"items"`
	SnapshotId  Id                         `json:"snapshot_id"`
	NextCursor  json.RawMessage            `json:"next_cursor"`
	Truncated   bool                       `json:"truncated"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *EvidencePage) UnmarshalJSON(data []byte) error {
	type plain EvidencePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v EvidencePage) MarshalJSON() ([]byte, error) {
	type plain EvidencePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type StreamEnvelope struct {
	StreamId        Id                         `json:"stream_id"`
	Sequence        Sequence                   `json:"sequence"`
	Type            string                     `json:"type"`
	ResourceRef     json.RawMessage            `json:"resource_ref"`
	ResourceVersion json.RawMessage            `json:"resource_version"`
	ObservedAt      DateTime                   `json:"observed_at"`
	CorrelationId   json.RawMessage            `json:"correlation_id"`
	ExtraFields     map[string]json.RawMessage `json:"-"`
}

func (v *StreamEnvelope) UnmarshalJSON(data []byte) error {
	type plain StreamEnvelope
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v StreamEnvelope) MarshalJSON() ([]byte, error) {
	type plain StreamEnvelope
	return encodeOpen(plain(v), v.ExtraFields)
}

type Problem struct {
	Type          string                     `json:"type"`
	Title         string                     `json:"title"`
	Status        int64                      `json:"status"`
	Detail        string                     `json:"detail"`
	Code          string                     `json:"code"`
	CorrelationId Id                         `json:"correlation_id"`
	RequestId     json.RawMessage            `json:"request_id"`
	RequestDomain json.RawMessage            `json:"request_domain"`
	CommandEffect string                     `json:"command_effect"`
	ResourceRef   json.RawMessage            `json:"resource_ref"`
	Details       map[string]json.RawMessage `json:"details"`
	ExtraFields   map[string]json.RawMessage `json:"-"`
}

func (v *Problem) UnmarshalJSON(data []byte) error {
	type plain Problem
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Problem) MarshalJSON() ([]byte, error) {
	type plain Problem
	return encodeOpen(plain(v), v.ExtraFields)
}

type Resource struct {
	Id             Id                         `json:"id"`
	State          string                     `json:"state"`
	Sequence       Sequence                   `json:"sequence"`
	ResourceKind   string                     `json:"resource_kind"`
	Source         Source                     `json:"source"`
	AllowedActions []string                   `json:"allowed_actions"`
	ExtraFields    map[string]json.RawMessage `json:"-"`
}

func (v *Resource) UnmarshalJSON(data []byte) error {
	type plain Resource
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Resource) MarshalJSON() ([]byte, error) {
	type plain Resource
	return encodeOpen(plain(v), v.ExtraFields)
}

type ResourcePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *ResourcePage) UnmarshalJSON(data []byte) error {
	type plain ResourcePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ResourcePage) MarshalJSON() ([]byte, error) {
	type plain ResourcePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type Bridge struct {
	Id                 Id                         `json:"id"`
	State              string                     `json:"state"`
	Sequence           Sequence                   `json:"sequence"`
	ResourceKind       string                     `json:"resource_kind"`
	Source             Source                     `json:"source"`
	AllowedActions     []string                   `json:"allowed_actions"`
	ManagementId       Id                         `json:"management_id"`
	OvsUuid            Id                         `json:"ovs_uuid"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ConfigRevision     Revision                   `json:"config_revision"`
	Name               string                     `json:"name"`
	PortRefs           []ResourceRef              `json:"port_refs"`
	DatapathType       string                     `json:"datapath_type"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Bridge) UnmarshalJSON(data []byte) error {
	type plain Bridge
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Bridge) MarshalJSON() ([]byte, error) {
	type plain Bridge
	return encodeOpen(plain(v), v.ExtraFields)
}

type Interface struct {
	Id                 Id                         `json:"id"`
	State              string                     `json:"state"`
	Sequence           Sequence                   `json:"sequence"`
	ResourceKind       string                     `json:"resource_kind"`
	Source             Source                     `json:"source"`
	AllowedActions     []string                   `json:"allowed_actions"`
	ManagementId       Id                         `json:"management_id"`
	OvsUuid            Id                         `json:"ovs_uuid"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ConfigRevision     Revision                   `json:"config_revision"`
	Name               string                     `json:"name"`
	PortRef            ResourceRef                `json:"port_ref"`
	InterfaceType      string                     `json:"interface_type"`
	Options            map[string]json.RawMessage `json:"options"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Interface) UnmarshalJSON(data []byte) error {
	type plain Interface
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Interface) MarshalJSON() ([]byte, error) {
	type plain Interface
	return encodeOpen(plain(v), v.ExtraFields)
}

type Bond struct {
	ManagementId       Id                         `json:"management_id"`
	OvsUuid            string                     `json:"ovs_uuid"`
	InstanceGeneration Id                         `json:"instance_generation"`
	ConfigRevision     Revision                   `json:"config_revision"`
	Name               string                     `json:"name"`
	BridgeRef          ResourceRef                `json:"bridge_ref"`
	InterfaceRefs      []ResourceRef              `json:"interface_refs"`
	Kind               string                     `json:"kind"`
	Vlan               VlanObservation            `json:"vlan"`
	OvsLinkState       map[string]json.RawMessage `json:"ovs_link_state"`
	LinuxCarrier       map[string]json.RawMessage `json:"linux_carrier"`
	AllowedOperations  []string                   `json:"allowed_operations"`
	Lacp               string                     `json:"lacp"`
	BondMode           string                     `json:"bond_mode"`
	MemberRefs         []ResourceRef              `json:"member_refs"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *Bond) UnmarshalJSON(data []byte) error {
	type plain Bond
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Bond) MarshalJSON() ([]byte, error) {
	type plain Bond
	return encodeOpen(plain(v), v.ExtraFields)
}

type User struct {
	Id          Id                         `json:"id"`
	Revision    Revision                   `json:"revision"`
	Username    string                     `json:"username"`
	Disabled    bool                       `json:"disabled"`
	RoleIds     []Id                       `json:"role_ids"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *User) UnmarshalJSON(data []byte) error {
	type plain User
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v User) MarshalJSON() ([]byte, error) {
	type plain User
	return encodeOpen(plain(v), v.ExtraFields)
}

type Role struct {
	Id           Id                         `json:"id"`
	Revision     Revision                   `json:"revision"`
	Name         string                     `json:"name"`
	Capabilities []string                   `json:"capabilities"`
	ExtraFields  map[string]json.RawMessage `json:"-"`
}

func (v *Role) UnmarshalJSON(data []byte) error {
	type plain Role
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Role) MarshalJSON() ([]byte, error) {
	type plain Role
	return encodeOpen(plain(v), v.ExtraFields)
}

type Token struct {
	Id          Id                         `json:"id"`
	Name        string                     `json:"name"`
	Scopes      []string                   `json:"scopes"`
	ExpiresAt   DateTime                   `json:"expires_at"`
	Revoked     bool                       `json:"revoked"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *Token) UnmarshalJSON(data []byte) error {
	type plain Token
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Token) MarshalJSON() ([]byte, error) {
	type plain Token
	return encodeOpen(plain(v), v.ExtraFields)
}

type TokenCreated struct {
	Id              Id                         `json:"id"`
	Name            string                     `json:"name"`
	Scopes          []string                   `json:"scopes"`
	ExpiresAt       DateTime                   `json:"expires_at"`
	Revoked         bool                       `json:"revoked"`
	Secret          string                     `json:"secret"`
	SecretAvailable bool                       `json:"secret_available"`
	ExtraFields     map[string]json.RawMessage `json:"-"`
}

func (v *TokenCreated) UnmarshalJSON(data []byte) error {
	type plain TokenCreated
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v TokenCreated) MarshalJSON() ([]byte, error) {
	type plain TokenCreated
	return encodeOpen(plain(v), v.ExtraFields)
}

type Metadata struct {
	Id          Id                         `json:"id"`
	Revision    Revision                   `json:"revision"`
	Kind        string                     `json:"kind"`
	Name        string                     `json:"name"`
	Description string                     `json:"description"`
	ExtraFields map[string]json.RawMessage `json:"-"`
}

func (v *Metadata) UnmarshalJSON(data []byte) error {
	type plain Metadata
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Metadata) MarshalJSON() ([]byte, error) {
	type plain Metadata
	return encodeOpen(plain(v), v.ExtraFields)
}

type Runtime struct {
	State               string                     `json:"state"`
	Scope               string                     `json:"scope"`
	ConfigurationReady  bool                       `json:"configuration_ready"`
	AuthenticationReady bool                       `json:"authentication_ready"`
	ExtraFields         map[string]json.RawMessage `json:"-"`
}

func (v *Runtime) UnmarshalJSON(data []byte) error {
	type plain Runtime
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v Runtime) MarshalJSON() ([]byte, error) {
	type plain Runtime
	return encodeOpen(plain(v), v.ExtraFields)
}

type ContractInfo struct {
	Major          int64                      `json:"major"`
	Version        string                     `json:"version"`
	OpenapiUrl     string                     `json:"openapi_url"`
	ServiceState   string                     `json:"service_state"`
	RequestDomains []string                   `json:"request_domains"`
	ExtraFields    map[string]json.RawMessage `json:"-"`
}

func (v *ContractInfo) UnmarshalJSON(data []byte) error {
	type plain ContractInfo
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ContractInfo) MarshalJSON() ([]byte, error) {
	type plain ContractInfo
	return encodeOpen(plain(v), v.ExtraFields)
}

type Subscription struct {
	Resources []map[string]json.RawMessage `json:"resources"`
	Cursor    json.RawMessage              `json:"cursor"`
}
type InterfaceSpec struct {
	Name    string                     `json:"name"`
	Type    string                     `json:"type"`
	Options map[string]json.RawMessage `json:"options"`
}
type BridgeCreateIntent struct {
	IntentId     Id     `json:"intent_id"`
	Operation    string `json:"operation"`
	ManagementId Id     `json:"management_id"`
	Name         string `json:"name"`
	DatapathType string `json:"datapath_type"`
}
type BridgeRemoveIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
}
type PortCreateIntent struct {
	IntentId     Id              `json:"intent_id"`
	Operation    string          `json:"operation"`
	ManagementId Id              `json:"management_id"`
	BridgeId     Id              `json:"bridge_id"`
	Name         string          `json:"name"`
	Interfaces   []InterfaceSpec `json:"interfaces"`
}
type PortRemoveIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
}
type InterfaceOptionsIntent struct {
	IntentId  Id                         `json:"intent_id"`
	Operation string                     `json:"operation"`
	Object    ObjectBinding              `json:"object"`
	Options   map[string]json.RawMessage `json:"options"`
	Mtu       json.RawMessage            `json:"mtu"`
}
type BondIntent struct {
	IntentId           Id            `json:"intent_id"`
	Operation          string        `json:"operation"`
	Object             ObjectBinding `json:"object"`
	Mode               string        `json:"mode"`
	Lacp               string        `json:"lacp"`
	MemberInterfaceIds []Id          `json:"member_interface_ids"`
}
type SpanningTreeIntent struct {
	IntentId     Id            `json:"intent_id"`
	Operation    string        `json:"operation"`
	Object       ObjectBinding `json:"object"`
	Protocol     string        `json:"protocol"`
	Priority     int64         `json:"priority"`
	ForwardDelay int64         `json:"forward_delay"`
	HelloTime    int64         `json:"hello_time"`
	MaxAge       int64         `json:"max_age"`
}
type MulticastIntent struct {
	IntentId          Id            `json:"intent_id"`
	Operation         string        `json:"operation"`
	Object            ObjectBinding `json:"object"`
	Snooping          bool          `json:"snooping"`
	FloodUnregistered bool          `json:"flood_unregistered"`
}
type MirrorIntent struct {
	IntentId           Id              `json:"intent_id"`
	Operation          string          `json:"operation"`
	Object             ObjectBinding   `json:"object"`
	Name               string          `json:"name"`
	SourcePortIds      []Id            `json:"source_port_ids"`
	DestinationPortIds []Id            `json:"destination_port_ids"`
	OutputPortId       json.RawMessage `json:"output_port_id"`
	OutputVlan         json.RawMessage `json:"output_vlan"`
}
type QoSIntent struct {
	IntentId   Id                           `json:"intent_id"`
	Operation  string                       `json:"operation"`
	Object     ObjectBinding                `json:"object"`
	Type       string                       `json:"type"`
	MaxRateBps int64                        `json:"max_rate_bps"`
	Queues     []map[string]json.RawMessage `json:"queues"`
}
type IsolationIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
	Protected bool          `json:"protected"`
}
type TelemetryIntent struct {
	IntentId       Id            `json:"intent_id"`
	Operation      string        `json:"operation"`
	Object         ObjectBinding `json:"object"`
	Protocol       string        `json:"protocol"`
	Targets        []string      `json:"targets"`
	Sampling       int64         `json:"sampling"`
	PollingSeconds int64         `json:"polling_seconds"`
}
type ProfileAssignmentIntent struct {
	IntentId        Id            `json:"intent_id"`
	Operation       string        `json:"operation"`
	Object          ObjectBinding `json:"object"`
	ProfileId       Id            `json:"profile_id"`
	ProfileRevision Revision      `json:"profile_revision"`
}
type ManagementNetworkIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
	Mtu       int64         `json:"mtu"`
	Addresses []string      `json:"addresses"`
	Gateways  []string      `json:"gateways"`
}
type ControllerIntent struct {
	IntentId  Id            `json:"intent_id"`
	Operation string        `json:"operation"`
	Object    ObjectBinding `json:"object"`
	Targets   []string      `json:"targets"`
	FailMode  string        `json:"fail_mode"`
}
type Intent = json.RawMessage
type ProfileCommand struct {
	RequestId   RequestId `json:"request_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Intents     []Intent  `json:"intents"`
}
type LabelCommand struct {
	RequestId   RequestId `json:"request_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}
type UserCreateCommand struct {
	RequestId RequestId `json:"request_id"`
	Username  string    `json:"username"`
	RoleIds   []Id      `json:"role_ids"`
	Password  string    `json:"password"`
}
type UserUpdateCommand struct {
	RequestId RequestId `json:"request_id"`
	Disabled  bool      `json:"disabled"`
	RoleIds   []Id      `json:"role_ids"`
}
type PasswordCommand struct {
	RequestId RequestId `json:"request_id"`
	Password  string    `json:"password"`
}
type RoleCommand struct {
	RequestId    RequestId `json:"request_id"`
	Name         string    `json:"name"`
	Capabilities []string  `json:"capabilities"`
}
type TokenCommand struct {
	RequestId RequestId `json:"request_id"`
	Name      string    `json:"name"`
	Scopes    []string  `json:"scopes"`
	ExpiresAt DateTime  `json:"expires_at"`
}
type EmptyCommand struct {
	RequestId RequestId `json:"request_id"`
}
type AAACommand struct {
	RequestId     RequestId                    `json:"request_id"`
	Servers       []map[string]json.RawMessage `json:"servers"`
	LocalFallback bool                         `json:"local_fallback"`
}
type CertificateCommand struct {
	RequestId      RequestId `json:"request_id"`
	CertificatePem string    `json:"certificate_pem"`
	PrivateKeyPem  string    `json:"private_key_pem"`
}
type SettingsCommand struct {
	RequestId RequestId `json:"request_id"`
	Locale    string    `json:"locale"`
	Theme     string    `json:"theme"`
	ViewMode  string    `json:"view_mode"`
}
type DiagnosticCommand struct {
	RequestId       RequestId                  `json:"request_id"`
	TemplateId      string                     `json:"template_id"`
	TargetRef       ResourceRef                `json:"target_ref"`
	DurationSeconds int64                      `json:"duration_seconds"`
	Options         map[string]json.RawMessage `json:"options"`
}
type CaptureCommand struct {
	RequestId       RequestId `json:"request_id"`
	InterfaceId     Id        `json:"interface_id"`
	DurationSeconds int64     `json:"duration_seconds"`
	MaxBytes        int64     `json:"max_bytes"`
	Filter          string    `json:"filter"`
}
type SupportCommand struct {
	RequestId    RequestId `json:"request_id"`
	IncludeKinds []string  `json:"include_kinds"`
	Redact       bool      `json:"redact"`
}
type LifecycleCommand struct {
	RequestId          RequestId `json:"request_id"`
	Operation          string    `json:"operation"`
	PreflightId        Id        `json:"preflight_id"`
	ExpectedGeneration Id        `json:"expected_generation"`
	Reason             string    `json:"reason"`
}
type RestoreCommand struct {
	RequestId          RequestId `json:"request_id"`
	BackupId           Id        `json:"backup_id"`
	VerificationId     Id        `json:"verification_id"`
	ExpectedGeneration Id        `json:"expected_generation"`
	Reason             string    `json:"reason"`
}
type ImportCommand struct {
	RequestId          RequestId `json:"request_id"`
	ArtifactId         Id        `json:"artifact_id"`
	ExpectedGeneration Id        `json:"expected_generation"`
	Mode               string    `json:"mode"`
}
type ArtifactCommand struct {
	RequestId  RequestId `json:"request_id"`
	UploadId   Id        `json:"upload_id"`
	Part       int64     `json:"part"`
	DataBase64 string    `json:"data_base64"`
	Final      bool      `json:"final"`
}
type OpenFlowCommand struct {
	RequestId        RequestId     `json:"request_id"`
	Object           ObjectBinding `json:"object"`
	ValidationId     Id            `json:"validation_id"`
	ExpectedRevision Revision      `json:"expected_revision"`
}
type OpenFlowPreflight struct {
	RequestId               RequestId     `json:"request_id"`
	Object                  ObjectBinding `json:"object"`
	Operation               string        `json:"operation"`
	SpecificationArtifactId Id            `json:"specification_artifact_id"`
}
type BridgePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Bridge                   `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *BridgePage) UnmarshalJSON(data []byte) error {
	type plain BridgePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v BridgePage) MarshalJSON() ([]byte, error) {
	type plain BridgePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type InterfacePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Interface                `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *InterfacePage) UnmarshalJSON(data []byte) error {
	type plain InterfacePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v InterfacePage) MarshalJSON() ([]byte, error) {
	type plain InterfacePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type VlanPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *VlanPage) UnmarshalJSON(data []byte) error {
	type plain VlanPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v VlanPage) MarshalJSON() ([]byte, error) {
	type plain VlanPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type BondPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Bond                     `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *BondPage) UnmarshalJSON(data []byte) error {
	type plain BondPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v BondPage) MarshalJSON() ([]byte, error) {
	type plain BondPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type SpanningTreePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *SpanningTreePage) UnmarshalJSON(data []byte) error {
	type plain SpanningTreePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v SpanningTreePage) MarshalJSON() ([]byte, error) {
	type plain SpanningTreePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type MulticastPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *MulticastPage) UnmarshalJSON(data []byte) error {
	type plain MulticastPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v MulticastPage) MarshalJSON() ([]byte, error) {
	type plain MulticastPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type TunnelPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *TunnelPage) UnmarshalJSON(data []byte) error {
	type plain TunnelPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v TunnelPage) MarshalJSON() ([]byte, error) {
	type plain TunnelPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type MirrorPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *MirrorPage) UnmarshalJSON(data []byte) error {
	type plain MirrorPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v MirrorPage) MarshalJSON() ([]byte, error) {
	type plain MirrorPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type QosPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *QosPage) UnmarshalJSON(data []byte) error {
	type plain QosPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v QosPage) MarshalJSON() ([]byte, error) {
	type plain QosPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type IsolationPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *IsolationPage) UnmarshalJSON(data []byte) error {
	type plain IsolationPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v IsolationPage) MarshalJSON() ([]byte, error) {
	type plain IsolationPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type FlowPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *FlowPage) UnmarshalJSON(data []byte) error {
	type plain FlowPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v FlowPage) MarshalJSON() ([]byte, error) {
	type plain FlowPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type GroupPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *GroupPage) UnmarshalJSON(data []byte) error {
	type plain GroupPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v GroupPage) MarshalJSON() ([]byte, error) {
	type plain GroupPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type MeterPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *MeterPage) UnmarshalJSON(data []byte) error {
	type plain MeterPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v MeterPage) MarshalJSON() ([]byte, error) {
	type plain MeterPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type ControllerPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *ControllerPage) UnmarshalJSON(data []byte) error {
	type plain ControllerPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ControllerPage) MarshalJSON() ([]byte, error) {
	type plain ControllerPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type EndpointPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *EndpointPage) UnmarshalJSON(data []byte) error {
	type plain EndpointPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v EndpointPage) MarshalJSON() ([]byte, error) {
	type plain EndpointPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type FdbEntryPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *FdbEntryPage) UnmarshalJSON(data []byte) error {
	type plain FdbEntryPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v FdbEntryPage) MarshalJSON() ([]byte, error) {
	type plain FdbEntryPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type NeighborPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *NeighborPage) UnmarshalJSON(data []byte) error {
	type plain NeighborPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v NeighborPage) MarshalJSON() ([]byte, error) {
	type plain NeighborPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type LldpNeighborPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *LldpNeighborPage) UnmarshalJSON(data []byte) error {
	type plain LldpNeighborPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v LldpNeighborPage) MarshalJSON() ([]byte, error) {
	type plain LldpNeighborPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type StatisticPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *StatisticPage) UnmarshalJSON(data []byte) error {
	type plain StatisticPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v StatisticPage) MarshalJSON() ([]byte, error) {
	type plain StatisticPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type DpdkPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *DpdkPage) UnmarshalJSON(data []byte) error {
	type plain DpdkPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v DpdkPage) MarshalJSON() ([]byte, error) {
	type plain DpdkPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type OffloadPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *OffloadPage) UnmarshalJSON(data []byte) error {
	type plain OffloadPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v OffloadPage) MarshalJSON() ([]byte, error) {
	type plain OffloadPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type TelemetryPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *TelemetryPage) UnmarshalJSON(data []byte) error {
	type plain TelemetryPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v TelemetryPage) MarshalJSON() ([]byte, error) {
	type plain TelemetryPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type CapabilityPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *CapabilityPage) UnmarshalJSON(data []byte) error {
	type plain CapabilityPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v CapabilityPage) MarshalJSON() ([]byte, error) {
	type plain CapabilityPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type DriftPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *DriftPage) UnmarshalJSON(data []byte) error {
	type plain DriftPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v DriftPage) MarshalJSON() ([]byte, error) {
	type plain DriftPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type CheckpointPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *CheckpointPage) UnmarshalJSON(data []byte) error {
	type plain CheckpointPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v CheckpointPage) MarshalJSON() ([]byte, error) {
	type plain CheckpointPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type DiagnosticTemplatePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *DiagnosticTemplatePage) UnmarshalJSON(data []byte) error {
	type plain DiagnosticTemplatePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v DiagnosticTemplatePage) MarshalJSON() ([]byte, error) {
	type plain DiagnosticTemplatePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type JobPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Job                      `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *JobPage) UnmarshalJSON(data []byte) error {
	type plain JobPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v JobPage) MarshalJSON() ([]byte, error) {
	type plain JobPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type TransactionPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Transaction              `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *TransactionPage) UnmarshalJSON(data []byte) error {
	type plain TransactionPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v TransactionPage) MarshalJSON() ([]byte, error) {
	type plain TransactionPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type BackupPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *BackupPage) UnmarshalJSON(data []byte) error {
	type plain BackupPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v BackupPage) MarshalJSON() ([]byte, error) {
	type plain BackupPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type CertificatePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Resource                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *CertificatePage) UnmarshalJSON(data []byte) error {
	type plain CertificatePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v CertificatePage) MarshalJSON() ([]byte, error) {
	type plain CertificatePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type ProfilePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Metadata                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *ProfilePage) UnmarshalJSON(data []byte) error {
	type plain ProfilePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v ProfilePage) MarshalJSON() ([]byte, error) {
	type plain ProfilePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type LabelPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Metadata                 `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *LabelPage) UnmarshalJSON(data []byte) error {
	type plain LabelPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v LabelPage) MarshalJSON() ([]byte, error) {
	type plain LabelPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type UserPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []User                     `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *UserPage) UnmarshalJSON(data []byte) error {
	type plain UserPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v UserPage) MarshalJSON() ([]byte, error) {
	type plain UserPage
	return encodeOpen(plain(v), v.ExtraFields)
}

type RolePage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Role                     `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *RolePage) UnmarshalJSON(data []byte) error {
	type plain RolePage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v RolePage) MarshalJSON() ([]byte, error) {
	type plain RolePage
	return encodeOpen(plain(v), v.ExtraFields)
}

type TokenPage struct {
	SnapshotId         Id                         `json:"snapshot_id"`
	InstanceGeneration json.RawMessage            `json:"instance_generation"`
	Items              []Token                    `json:"items"`
	NextCursor         json.RawMessage            `json:"next_cursor"`
	Truncated          bool                       `json:"truncated"`
	ExtraFields        map[string]json.RawMessage `json:"-"`
}

func (v *TokenPage) UnmarshalJSON(data []byte) error {
	type plain TokenPage
	return decodeOpen(data, (*plain)(v), &v.ExtraFields)
}
func (v TokenPage) MarshalJSON() ([]byte, error) {
	type plain TokenPage
	return encodeOpen(plain(v), v.ExtraFields)
}
